### PR TITLE
fix(date-pickers): validation message when validity flags are true

### LINKED ISSUE #397: DatePicker error in console when required property is passed
**Before submitting a bug:**

- [x] Is this reproducible in the latest version of Shidoka?
- [ ] Is this reproducible in the [Shidoka Storybook](https://shidoka-applications.netlify.app)?
- [ ] Is this reproducible in a [Sandbox](https://codesandbox.io)?
- If it's not reproducible in any of the above scenarios, please do not open a bug report as it is an application-level issue.

**Describe the bug**

Following TypeError is seen in the console when the datepicker, date-range picker, or timepicker is `required`:

`datepicker.js:305 Uncaught (in promise) TypeError: Failed to execute 'setValidity' on 'ElementInternals': The second argument should not be empty if one or more flags in the first argument are true.    at E._validate (datepicker.js:305:25)     at E._onUpdated (form-input.js:14:79)     at E.updated (form-input.js:17:18)     at E.updated (datepicker.js:181:15)     at E._$AE (lit-element-3185f710.js:254:83)     at E.performUpdate (lit-element-3185f710.js:246:19)     at E.scheduleUpdate (lit-element-3185f710.js:230:21)     at E._$Ej (lit-element-3185f710.js:226:24)     at async E.firstUpdated (datepicker.js:178:243)`

**To Reproduce**

Not reproducible in Storybook.

The error occurred because when `required` was set to true and the input value was empty, the code was setting valueMissing=true in the validity state but potentially had no validation message if defaultErrorMessage was empty.

**Expected behavior**

Console error is not present when `required` prop is passed.

**Screenshots**

**Environment**

- OS: Mac -- Sequoia 15.3.1
- Browser: Chrome, Safari
- Version: Chrome v133.0.6943.127

### PR DESCRIPTION
**Pull request by wbarbee**
## Summary

fixes #397 
fixes [AB#2132841](https://dev.azure.com/Kyndryl/f7f7ab25-06ec-43dc-902d-dee2e157cebd/_workitems/edit/2132841)

## Notes

Error was occurring for dev who raised the Issue because, when datepicker (or timepicker or date-range picker) was required and the input value was empty, the code was setting valueMissing=true in the validity state but potentially had no validation message if defaultErrorMessage was empty.

## Checklist

- [x] Used Conventional Commit messages as outlined in the contributing guide.
  - [ ] Noted breaking changes (if any).
- [ ] Documented/updated all props, events, slots, parts, etc with JSDoc.
  - [ ] Ran the `analyze` command to update Storybook docs.
- [ ] Added/updated Stories with controls to cover all variants.
- [x] Ran `test` locally to address any failures.
- [ ] Added/updated the Figma link for the Story's Design tab.
- [ ] Added any new component exports to the src/index.ts file

### CODE REVIEW

**Review by tulasigudibanda — APPROVED** [review]

File: src/components/reusable/datePicker/datepicker.ts [hunk 1]
```diff
@@ -584,7 +584,7 @@ export class DatePicker extends FormMixin(LitElement) {
 
     if (isRequired && isEmpty) {
       validity = { ...validity, valueMissing: true };
-      validationMessage = this.defaultErrorMessage;
+      validationMessage = this.defaultErrorMessage || 'Please select a date';
```
Comment (brian-patrick-3) [inline src/components/reusable/datePicker/datepicker.ts:587]: Hard coding these strings does not allow the application to provide translations if needed.

**Review by brian-patrick-3 — CHANGES_REQUESTED** [review]

File: src/components/reusable/datePicker/datepicker.ts (hunk 1 above)
Comment (wbarbee) [reply src/components/reusable/datePicker/datepicker.ts]: ✅
